
default: &default
  adapter: postgresql
  encoding: unicode
  username: obstacle_detection
  password: obstacle_detection
  pool: 5
  host: localhost

development:
  <<: *default
  database: obstacle_detection_development

test:
  <<: *default
  database: obstacle_detection_test

production:
  <<: *default
database: obstacle_detection_production
